# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to='imager_profile.ImagerProfile'),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('nature', 'Nature'), ('family', 'Family'), ('travel', 'Travel'), ('art', 'Art'), ('food', 'Food')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='region',
            field=models.CharField(choices=[('pnw', 'Pacific Northwest'), ('wc', 'West Coast'), ('sw', 'South West'), ('mw', 'Midwest'), ('s', 'Southern U.S.'), ('ec', 'East Coast'), ('ne', 'New England'), ('ak', 'Alaska'), ('h', 'Hawaii'), ('t', 'U.S. Territory')], max_length=30),
        ),
    ]
