# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160412_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.TextField(default=''),
        ),
    ]
