# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160412_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
