# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160413_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='cover_photo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='imager_images.Album'),
        ),
    ]
